# Change these first
owner: m-fr # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: m-fr
    url: https://www.m-fr.cz

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.m-fr.cz
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /
  logoUrl: https://raw.githubusercontent.com/m-fr/upptime/master/mfr-upptime.svg
  name: Upptime
  introTitle: "Monitoring of **m-fr** site done by **Upptime**."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Site
      href: https://www.m-fr.cz
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/m-fr

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
